# Generated by Django 5.2.6 on 2025-10-17 22:58

import materials.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(
                validators=[materials.validators.validate_youtube_url]
            ),
        ),
    ]
